[build]
  publish = "."
  command = "echo 'No build required - static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/x-icon"

[[headers]]
  for = "/favicon-*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Custom domain settings
[[redirects]]
  from = "https://paritoshlamsal25.github.io/Personal--Portfolio--Development/*"
  to = "https://paritosh.com.np/:splat"
  status = 301
  force = true
